# Generated by Django 5.1.4 on 2025-01-01 10:35

import blogs.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blogs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="image",
            field=models.ImageField(
                default="def.jpg", upload_to=blogs.models.blog_image_upload_path
            ),
        ),
    ]
