version: '3'

services:
  backend:
    build:
      context: ./backend   # Point to the backend directory
    volumes:
      - ./backend:/app     # Mount the backend directory
    ports:
      - "8000:8000"        # Expose backend on port 8000
    depends_on:
      - db                 # Wait for the database service to start
    environment:
      - DEBUG=1
      - DJANGO_DB_HOST=localhost
      - DJANGO_DB_PORT=5432
      - DJANGO_DB_NAME=abhayt
      - DJANGO_DB_USER=postgres
      - DJANGO_DB_PASSWORD=password

  frontend:
    build:
      context: ./frontend  # Point to the frontend directory
    volumes:
      - ./frontend:/app    # Mount the frontend directory
    ports:
      - "3000:3000"        # Expose frontend on port 3000
    environment:
      - REACT_APP_API_URL=http://backend:8000   # Connect to the backend

  db:
    image: postgres:13       # Postgres database image
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"          # Expose database on port 5432

volumes:
  postgres_data:
